name: My First Workflow
on:
  push:
    branches: 
      - main
jobs:
  myFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: My First Step
        run: printenv
      - name: My Second Step
        run: |
          echo "Amigoscode"
          echo "Hello" > file.txt
          ls
          echo file.text
      - name: Sleep Step
        run: sleep 20
