name: My First Workflow
on:
  push:
    branches: 
      - main
jobs:
  myFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: My First Action
        uses: actions/checkout@v4
      - name: My First Step
        run: printenv
      - name: My Second Step
        run: |
          echo "Amigoscode"
          echo "Hello" > file.txt
          ls
          cat file.txt
      - name: Sleep Step
        run: sleep 5
      - name: ls repo
        run: |
          ls
